### ISSUE TITLE
several questions...

### ISSUE THREAD

**Issue by emilianox** [leoomi/LinuxLGGramScripts#1]
Hi, first of all, thanks for make this repo, its help me a lot(really) with the config on the new laptop...

i have a few questions:

Is fn+f5 works for enable/disable the touchpad?
How the battery_care_limit works? i just run the script but when i run cat on the file its return 0 all the time and the battery continues charging to 100%

I have the 14Z90N model on ubuntu 20.04

Again, thanks for the repo!

**Comment by leoomi** [comment]
Hi @emilianox, it's been a bit since I wrote these scripts and I don't remember a lot about then.
I have been using the battery_care_limit one for sure, I never get above 80% charge. I'm pretty sure it's supposed to have either "80" or "100" to set the maximum battery charge, so it's odd that it's 0 for you.
As for fn+f5 I believe it never worked for me, but I'll check this later.

I believe your model 14Z90N is a newer model, I only tested the drivers on mine (15Z980), so that might be a big factor here.
I'll test some things out and I'll at least update the README to mention the specific model I use if I'm not able to help you.

**Comment by leoomi** [comment]
Hi @emilianox.

I've done some testing here and I believe the current drivers for the LG Gram might not be compatible with your model.
battery_care_limit here would spirt out errors if I tried to set its value to anything but 80 or 100. I guess the drivers might are not actively being updated for the newer version or might be WIP. For this, you might want to open issue for the linux kernel, maybe? 
Matan Ziv-Av <matan@svgalib.org> might be able to know how to proceed.

Also, it seems that fn+f5 only opens displays settings for me, but I don't if I was the one who configured this or not.

I'll update the readme and close this issue.
